#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     US,             sensorSONAR)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     motorNom,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorPulley,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorBL,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorBR,       tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_1,    box,                  tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    feet,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------+
|                                														|
| Last Edited: Meet Patel and Mattori Burn-Baby-Baum 2/16/15|
|																														|
+----------------------------------------------------------*/

#include "JoystickDriver.c"

//Constants
const int THRESHOLD = 27;


task main()
{
	waitForStart();
	//make sure there is a threshold the joystick values have to pass to move the motors
	//the motors might stop if we have values that are too low
	//sautonomous();

	//autonomous();
	//The manual event loop
	bool started = false;
	nMotorEncoder[motorPulley] = 0;
	nMotorEncoder[motorBL] = 0;
	nMotorEncoder[motorBR] = 0;
 while(true)
  {
  	//nxtDisplayTextLine(3, "BR encoder %d", nMotorEncoder[motorBR]);
  	nxtDisplayTextLine(4, "BL encoder %d", nMotorEncoder[motorBL]);
  	nxtDisplayTextLine(5, "p encoder: %d", nMotorEncoder[motorPulley]);
  	nxtDisplayTextLine(3, "sensor: %d", SensorValue[US]);
    getJoystickSettings(joystick);  // Update Buttons and Joysticks

    //nxtDisplayTextLine(3, "j1y1 %d", joystick.joy1_y1);
    //nxtDisplayTextLine(4, "j1y2 %d", joystick.joy1_y2);

    //i drive...
    switch(joystick.joy1_TopHat) {
   		case 7: case 0: case 1: if(started) { motor[motorBL] = 20; motor[motorBR] = 20; motor[motorFL] = 20; motor[motorFR] = 20; } break;
   		case 3: case 4: case 5: motor[motorBL] = -20; motor[motorBR] = -20; motor[motorFL] = -20; motor[motorFR] = -20; break;
   		default:
   			short y1 = joystick.joy1_y1;
		    short y2 = joystick.joy1_y2;
		    //Threshold is 27 right now see above declaration ^^
		    if(abs(y1) < THRESHOLD) {
		    	y1 = 0;
		  	} else started = true;

		    if(abs(y2) < THRESHOLD) {
		    	y2 = 0;
		    } else started = true;

		    motor[motorBL] = y1/1.28;
		    motor[motorFL] = y1/1.28;

		    motor[motorBR] = y2/1.28;
		    motor[motorFR] = y2/1.28;
  	}

    //nxtDisplayTextLine(1, "y1: %d", joystick.joy1_y1);
    //nxtDisplayTextLine(2, "left: %d", motor[motorFL]);
    //nxtDisplayTextLine(3, "y2: %d", joystick.joy1_y2);
    //nxtDisplayTextLine(4, "right: %d", motor[motorFR]);

    //GÜNthER
    short tophat = joystick.joy2_TopHat;
    switch(tophat) {
    	case 7: case 0: case 1: if(started) { motor[motorPulley] = 100; } break;
    	case 3: case 4: case 5: motor[motorPulley] = -40;  break;
    	default: motor[motorPulley] = 0;
  	}

		/*if(joy2Btn(5) == 1) {
			motor[motorNom] = 60;
			started = true;
		}*/

		if(joy2Btn(4) == 1) {
			motor[motorNom] = -100;
			started = true;
		}
		else {
			motor[motorNom] = 0;
		}

  	if(joy2Btn(2) == 1) {
  		servo[box] = 0;
  		//wait1Msec(50);
  	}
  	else servo[box] = 220;

  	if(joy2Btn(5) == 1) {
  		servo[feet] = 80;
		}
		else if (joy2Btn(7) == 1) {
			servo[feet] = 0;
		}
		//servo[feet] = 0;

  	//nxtDisplayTextLine(5, "started: %s", started);
  	//nxtDisplayTextLine(6, "pulley: %d", motor[motorPulley]);
		//nxtDisplayTextLine(7, "encoder: %d", nMotorEncoder[motorPulley]);

  	}
}

/**
* ACTUAL BUTTON MAPPINGS
start = 8
back = 7
RB = 6
LB = 5
Y = 4
B = 3
A = 2
X = 1

*/
